### ISSUE TITLE
Room Number

### ISSUE THREAD

**Issue by Carbiner** [SiliconLion/schoolMap#16]
We need each room node to have a room number, and also an abstract room number, and also a title.
The actual room numbers will have to be added into code after we leave, because the chance that we'll actually know what they are to be able to plug them in is minimal at best.

The actual room number and title will be displayed when the people select where they are and where they want to go.

**Comment by SmithSAC** [comment]
So, we want to draw the room number over the room on the map when people select that specific room?

**Comment by Carbiner** [comment]
This is no longer an issue because the room object has this now.
