### ISSUE TITLE
Rooms!

### ISSUE THREAD

**Issue by SiliconLion** [SiliconLion/schoolMap#17]
### we want a room object that contains the following variables 
- room number
- room name
- array of corners or borders
### we want a room object that contains the following methods
- 'draw' method that draws using the array of corners or borders. may want to reference this S.O. https://stackoverflow.com/questions/4839993/how-to-draw-polygons-on-an-html5-canvas 
### optionally
- some way to assign where the door(s) is. we may need to discus this one. If there isn't a strong idea for a good way to do this, feel free to put it on the back burner. Or go ahead and just try to make something that works
- room highlights when mouse hovers over it. 
    - create an algorithm to check if the mouse is within an arbitrary perimeter. Alternatively, use someone else's algorithm. Alternatively, there may already be a method or function for this. Get creative!
    - create a way to handle/check mouse movement (it's easier than it sounds I promise.) 
    - adjust the mouse coordinates to the canvas coordinates. Use something like 
```
  var xCoord = event.clientX - myCanvas.getBoundingClientRect().left;
  var yCoord = event.clientY - myCanvas.getBoundingClientRect().top;
  exampFunc(xCoord, yCoord);
```
where exampFunc is whatever function you are passing the adjusted coordinates to.

# Remember to do this in a new branch

**Comment by SmithSAC** [comment]
GO TO SLEEP DAVID!

**Comment by SiliconLion** [comment]
I can't sleep :"( . I'm afflicted.

**Comment by SmithSAC** [comment]
The basic requirements are fulfilled in the 2/20/2018 push of the RoomObjectCreation branch. The optional features are still WIP.

**Comment by SmithSAC** [comment]
Push: (2/28/2018)
+Added the ability to draw rooms using only two corners inputs.
+Made rooms filled in when they are drawn.

**Comment by Carbiner** [comment]
Rooms are functional in our current version. 20180320

**Comment by SiliconLion** [comment]
Room numbers will be added later
