### ISSUE TITLE
Sync the room object with the room node / only create a room if all conditions are met

### ISSUE THREAD

**Issue by SmithSAC** [SiliconLion/schoolMap#26]
We want room nodes and room objects to be able to recognize their counterpart. This can be done by having the user select a pre-created room node be selected during the corner selection portion of the room creation process.

Also add a clause to the connectCorners() function so that rooms are not created if all the creation criteria ,including a corresponding room node, are not declared during room creation.

I'm mostly writing this as a reminder for myself. I can do it.

**Comment by SiliconLion** [comment]
This works now. Done using the hidden map.
